# -*- coding: utf-8 -*-
"""Program1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i4Ev203XL7Lmwn73X0xZvA96dsOGswae

ARRAY OPERATIONS
"""

import numpy as np
array_from_list=np.array([1,2,3,4,5])
print("Array from list:",array_from_list)

array_with_range=np.arange(10)
print("Array with range:",array_with_range)





zeros_array=np.zeros((3,3))
print("Array of zeros:\n",zeros_array)

ones_array=np.ones((2,5))
print("Array of ones:\n",ones_array)

